run:
	sudo docker compose up --remove-orphans
build:
	sudo docker compose up -d --build
down:
	sudo docker compose down -v --remove-orphans
downs:
	sudo docker compose down -v $(s)
builds:
	sudo docker compose up --build $(s)
